namespace SharedModels.Enum
{
    public enum ErrorCodes
    {
        CHANGES_NOT_SAVED = 100,
        PROJECT_HAS_OPEN_TASKS = 101,
        PROJECT_NOT_FOUND = 102,
        USER_NOT_FOUND = 103,
        EMPLOYEE_IS_IN_PROJECT = 104,
        EMPLOYEE_ISNT_IN_PROJECT = 105,
        INVALID_REQUEST = 106,
        ROLE_NOT_FOUND = 107,
        PROJECTS_NOT_FOUND = 108,
        TASKS_NOT_FOUND = 109,
        TASK_NOT_FOUND = 110,
        USER_RESTRICTED = 111,
        USER_HAS_OPENED_TASKS = 112,
        TASK_IS_DONE = 113,
        TASK_IS_ASSIGNED_TO_ANOTHER_EMPLOYEE = 114,
        TASK_IS_ALREADY_ASSIGNED = 115,
        EMPLOYEE_NOT_PART_OF_PROJECT = 116,
        TASK_CREATED_BY_ANOTHER_USER = 117,
        TASK_IS_OPEN = 118,
        USERNAME_ALREADY_USED = 119,
        EMAIL_ALREADY_USED = 120,
        CODE_ALREADY_USED = 121,
        EMPLOYEE_NOT_FOUND = 122,
        EMPLOYEE_HAS_OPENED_TASKS = 123,
        VALID_REQUEST = 200,
        UNAUTHORIZED = 403,
        RECORD_NOT_FOUND = 404,
        BAD_REQUEST = 500
    }
}
